Add `atmos describe dependants` command. Update docs
cloudposse/atmos pull request #339
Opened 2023-03-13 03:25 UTC by aknysh

## what

* Fix an issue when the terraform components were in subfolders in the `components/terraform` folder deeper than the second level
* Add `atmos describe dependants` command
* Update docs https://pr-339.atmos-docs.ue2.dev.plat.cloudposse.org/cli/commands/describe/dependants/

## why

* Fix an issue when the terraform components were in subfolders in the `components/terraform` folder deeper than second level. For example:

     <img width="241" alt="image" src="https://user-images.githubusercontent.com/7356997/224600584-d77e3fe6-a7a4-4d6d-a691-7cd2a5603963.png">

    The component `test-component-2` is in the subfolder `components/terraform/test/test2`, for which the filesystem path to the generated `varfile` was created incorrectly (when used just `components/terraform/test` subfolder, it was correct). The PR fixes the issue, and now components can be in any subfolder at any level. 

* The `atmos describe dependants` command produces a list of Atmos components in Atmos stacks that depend on the provided Atmos component

## description

In Atmos, you can define component dependencies by using the `settings.depends_on` section. The section used to define all the Atmos components (in the same or different stacks) that the current component depends on.

The `settings.depends_on` section is a map of objects. The map keys are just the descriptions of dependencies and can be strings or numbers. Provide meaningful descriptions so that people can understand what the dependencies are about.

Each object in the `settings.depends_on` section has the following schema:

- `component` (required) - an Atmos component that the current component depends on
- `namespace` (optional) - the `namespace` where the Atmos component is provisioned
- `tenant` (optional) - the `tenant` where the Atmos component is provisioned
- `environment` (optional) - the `environment` where the Atmos component is provisioned
- `stage` (optional) - the `stage` where the Atmos component is provisioned

The `component` attribute is required. The rest are the context variables and are used to define Atmos stacks other than the current stack. For example, you can specify:

- `namespace` if the `component` is from a different Organization
- `tenant` if the `component` is from a different Organizational Unit
- `environment` if the `component` is from a different region
- `stage` if the `component` is from a different account
- `tenant`, `environment` and `stage` if the component is from a different Atmos stack (e.g. `tenant1-ue2-dev`)

<br/>

In the following example, we define that the `top-level-component1` component depends on the following:

- The `test/test-component-override` component in the same Atmos stack
- The `test/test-component` component in Atmos stacks identified by the `dev` stage
- The `my-component` component from the `tenant1-ue2-staging` Atmos stack

```yaml title="examples/complete/stacks/catalog/terraform/top-level-component1.yaml"
components:
  terraform:
    top-level-component1:
      settings:
        depends_on:
          "1":
            # If the `context` (namespace, tenant, environment, stage) is not provided, 
            # the `component` is from the same Atmos stack as this component
            component: "test/test-component-override"
          "2":
            # This component (in any stage) depends on `test/test-component` 
            # from the `dev` stage (in any `environment` and any `tenant`)
            component: "test/test-component"
            stage: "dev"
          "3":
            # This component depends on `my-component` 
            # from the `tenant1-ue2-staging` Atmos stack
            component: "my-component"
            tenant: "tenant1"
            environment: "ue2"
            stage: "staging"
      vars:
        enabled: true
```

In the following example, we specify that the `top-level-component2` component depends on the following:

- The `test/test-component` component in the same Atmos stack
- The `test/test2/test-component-2` component in the same Atmos stack

```yaml title="examples/complete/stacks/catalog/terraform/top-level-component2.yaml"
components:
  terraform:
    top-level-component2:
      metadata:
        component: "top-level-component1"
      settings:
        depends_on:
          "1":
            # If the `context` (namespace, tenant, environment, stage) is not provided, 
            # the `component` is from the same Atmos stack as this component
            component: "test/test-component"
          "2":
            # If the `context` (namespace, tenant, environment, stage) is not provided, 
            # the `component` is from the same Atmos stack as this component
            component: "test/test2/test-component-2"
      vars:
        enabled: true
```

<br/>

Having the `top-level-component` and `top-level-component2` components configured as shown above, we can now execute the following Atmos command to show all the components and stacks that are dependants of the `test/test-component` component in the `tenant1-ue2-dev` stack:

```shell
atmos describe dependants test/test-component -s tenant1-ue2-dev
```

```json
[
  {
    "component": "top-level-component1",
    "component_type": "terraform",
    "component_path": "examples/complete/components/terraform/top-level-component1",
    "namespace": "cp",
    "tenant": "tenant1",
    "environment": "ue2",
    "stage": "dev",
    "stack": "tenant1-ue2-dev",
    "spacelift_stack": "tenant1-ue2-dev-top-level-component1",
    "atlantis_project": "tenant1-ue2-dev-top-level-component1"
  }
]
```

Similarly, the following Atmos command shows all the components and stacks that are dependants of the `test/test-component` component in the `tenant1-ue2-test-1` stack:

```shell
atmos describe dependants test/test-component -s tenant1-ue2-test-1
```

```json
[
  {
    "component": "top-level-component1",
    "component_type": "terraform",
    "component_path": "examples/complete/components/terraform/top-level-component1",
    "namespace": "cp",
    "tenant": "tenant1",
    "environment": "ue2",
    "stage": "test-1",
    "stack": "tenant1-ue2-test-1",
    "spacelift_stack": "tenant1-ue2-test-1-top-level-component1",
    "atlantis_project": "tenant1-ue2-test-1-top-level-component1"
  },
  {
    "component": "top-level-component2",
    "component_type": "terraform",
    "component_path": "examples/complete/components/terraform/top-level-component1",
    "namespace": "cp",
    "tenant": "tenant1",
    "environment": "ue2",
    "stage": "test-1",
    "stack": "tenant1-ue2-test-1",
    "atlantis_project": "tenant1-ue2-test-1-top-level-component2"
  }
]
```

<br/>

After the `test/test-component` has been provisioned, you can use the outputs to perform the following actions:

- Provision the dependent components by executing the Atmos commands `atmos terraform apply top-level-component1 -s tenant1-ue2-test-1` and `atmos terraform apply top-level-component2 -s tenant1-ue2-test-1` (on the command line or from a GitHub Action)

- Trigger the dependent Spacelift stack (from a GitHub Action by using the [spacectl](https://github.com/spacelift-io/spacectl) CLI, or by using an OPA [Trigger](https://docs.spacelift.io/concepts/policy/trigger-policy) policy, or by using the [spacelift_stack_dependency](https://registry.terraform.io/providers/spacelift.io/spacelift/latest/docs/resources/stack_dependency) resource)

- Trigger the dependent Atlantis project

## related
* Closes https://github.com/cloudposse/atmos/issues/333

2023-03-14 05:50 UTC, jamengual commented
when running :
```
atmos describe dependants test/test-component -s tenant1-ue2-test-1
```
the output order is in the order of dependency?

I do not know if the order of execution could be an easy output to add

2023-03-15 15:04 UTC, mcalhoun requested changes
Overall this looks good...I made a couple of small comments/requests.

2023-03-15 19:54 UTC, aknysh commented
> when running :
> 
> ```
> atmos describe dependants test/test-component -s tenant1-ue2-test-1
> ```
> 
> the output order is in the order of dependency?
> 
> I do not know if the order of execution could be an easy output to add

In `settings.depends_on` we specify the components that the current component depends on.
Then, when executing `atmos describe dependants <component> -s <stack>`, we get back the dependants of the `component` in the command, not the original component, so there is no way to specify order. You get back a list of components/stacks, and you can trigger them in any order, they should be able to run in parallel.

For example, below we specify that the `eks` and `rds` components depend on the `vpc` component in the same stack:

```yaml
components:
   terraform:
      eks:
         settings:
            depends_on:
              1:
                 component: vpc
```

```yaml
components:
   terraform:
      rds:
         settings:
            depends_on:
              1:
                 component: vpc
```


Then, we provision (or update) the `vpc` component by running

```shell
atmos terraform apply vpc -s <stack>
```

Then we want to know what components depend on the `vpc` component (so they can be triggered)

```shell
atmos describe dependants vpc -s <stack>
```

We get back the following:

```json
[
   {
      "component": "eks",
      "component_type": "terraform",
      "stack": "....",
      "stack_slug": "....",
      "atlantis_project": "...."
   },
   {
      "component": "rds",
      "component_type": "terraform",
      "stack": "....",
      "stack_slug": "....",
      "spacelift_stack": "....",
      "atlantis_project": "...."
   }
]
```

Then we trigger the dependent components to check if they need to be updated after the `vpc` component was changed

```shell
atmos terraform plan eks -s <stack>
atmos terraform plan eks -s <stack>
```

After that you can run commands

```shell
atmos describe dependants eks -s <stack>
atmos describe dependants rds -s <stack>
```

to see if those components have dependencies that need to be run.

@jamengual

2023-03-15 21:20 UTC, mcalhoun approved these changes
LGTM!

2023-03-15 21:44 UTC, merged

2023-03-16 00:21 UTC, jamengual commented
> > when running :
> > 
> > ```
> > atmos describe dependants test/test-component -s tenant1-ue2-test-1
> > ```
> > 
> > the output order is in the order of dependency?
> > 
> > I do not know if the order of execution could be an easy output to add
> 
> In `settings.depends_on` we specify the components that the current component depends on.
> Then, when executing `atmos describe dependants <component> -s <stack>`, we get back the dependants of the `component` in the command, not the original component, so there is no way to specify order. You get back a list of components/stacks, and you can trigger them in any order, they should be able to run in parallel.
> 
> For example, below we specify that the `eks` and `rds` components depend on the `vpc` component in the same stack:
> 
> ```yaml
> components:
>    terraform:
>       eks:
>          settings:
>             depends_on:
>               1:
>                  component: vpc
> ```
> 
> ```yaml
> components:
>    terraform:
>       rds:
>          settings:
>             depends_on:
>               1:
>                  component: vpc
> ```
> 
> 
> Then, we provision (or update) the `vpc` component by running
> 
> ```shell
> atmos terraform apply vpc -s <stack>
> ```
> 
> Then we want to know what components depend on the `vpc` component (so they can be triggered)
> 
> ```shell
> atmos describe dependants vpc -s <stack>
> ```
> 
> We get back the following:
> 
> ```json
> [
>    {
>       "component": "eks",
>       "component_type": "terraform",
>       "stack": "....",
>       "stack_slug": "....",
>       "atlantis_project": "...."
>    },
>    {
>       "component": "rds",
>       "component_type": "terraform",
>       "stack": "....",
>       "stack_slug": "....",
>       "spacelift_stack": "....",
>       "atlantis_project": "...."
>    }
> ]
> ```
> 
> Then we trigger the dependent components to check if they need to be updated after the `vpc` component was changed
> 
> ```shell
> atmos terraform plan eks -s <stack>
> atmos terraform plan eks -s <stack>
> ```
> 
> After that you can run commands
> 
> ```shell
> atmos describe dependants eks -s <stack>
> atmos describe dependants rds -s <stack>
> ```
> 
> to see if those components have dependencies that need to be run.
> 
> @jamengual 
> 
Thanks @aknysh that makes sense.